apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: workloads
  namespace: argocd

spec:
  description: Business workload applications

  sourceRepos:
    - https://github.com/isw-Prashant/gitops-platform-lab.git

  destinations:
    - namespace: demo
      server: https://prod-control-plane:6443

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"