apiVersion: v1
kind: Service

metadata:
  name: {{ include "frontend.fullname" . }}

spec:
  selector:
    app: {{ .Values.labels.app }}

  ports:
    - port: {{ .Values.service.port }}

      targetPort: {{ .Values.service.port }}

  type: {{ .Values.service.type }}
