apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: cluster-demo
  namespace: argocd

spec:
  goTemplate: true

  generators:
    - clusters: {}

  template:
    metadata:
      name: "sample-nginx-{{ .nameNormalized }}"

    spec:
      project: default

      source:
        repoURL: https://github.com/isw-Prashant/gitops-platform-lab.git
        targetRevision: HEAD
        path: applications/sample-nginx

      destination:
        server: "{{ .server }}"
        namespace: demo

      syncPolicy:
        automated:
          prune: true
          selfHeal: true