replicaCount: 2
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.29"
service:
  type: ClusterIP
  port: 80  
resources: {}
labels:
  app: nginx
ingress:
  enabled: True
  host: sample.local

service:
  type: ClusterIP
