replicaCount: 2
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.29"
service:
  type: ClusterIP
  port: 80
  targetPort: 80
resources: {}
labels:
  app: frontend
ingress:
  enabled: True
  host: sample.local